/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/ui/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))', foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))', 'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))', 'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))', ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: { lg: 'var(--radius)', md: 'calc(var(--radius) - 2px)', sm: 'calc(var(--radius) - 4px)' },
      // Legacy aegis tokens mapped to shadcn equivalents (for Sidebar compat)
      backgroundColor: {
        'surface': 'hsl(var(--secondary))',
        'surface-secondary': 'hsl(var(--muted))',
        'surface-tertiary': 'hsl(220 13% 18%)',
        'surface-cream': 'hsl(220 13% 12%)',
        'panel': 'hsl(var(--background))',
        'panel-muted': 'hsl(var(--muted))',
        'accent-light': 'hsla(160 72% 41% / 0.15)',
        'accent-subtle': 'hsla(160 72% 41% / 0.07)',
        'error': 'hsl(var(--destructive))',
        'error-light': 'hsla(0 72% 51% / 0.15)',
        'success': 'hsl(142 76% 36%)',
        'info': 'hsl(199 89% 48%)',
      },
      textColor: {
        'muted': 'hsl(var(--muted-foreground))',
        'muted-light': 'hsl(220 8% 40%)',
        'ink-900': 'hsl(var(--foreground))',
        'ink-800': 'hsl(var(--foreground))',
        'ink-700': 'hsl(var(--muted-foreground))',
        'ink-600': 'hsl(var(--muted-foreground))',
        'ink-500': 'hsl(220 8% 40%)',
        'ink-400': 'hsl(220 8% 30%)',
        'accent': 'hsl(var(--accent))',
        'error': 'hsl(var(--destructive))',
        'success': 'hsl(142 76% 36%)',
        'info': 'hsl(199 89% 48%)',
      },
      borderColor: {
        'ink-900/5': 'hsla(220 13% 18% / 0.5)',
        'ink-900/10': 'hsl(var(--border))',
        'ink-900/20': 'hsla(220 13% 18% / 1)',
        'accent/30': 'hsla(160 72% 41% / 0.3)',
        'accent/60': 'hsla(160 72% 41% / 0.6)',
      },
    },
  },
  plugins: [],
}
